import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import AddHabit from '../components/AddHabit';
import HabitCalendar from '../components/HabitCalendar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header content={'Hello world!'} />
        <HabitCalendar />
        <AddHabit />
      </main>
    </div>
  );
};

export default Home;
